# makefile

all:
	@echo "Preheating and cooking for a short time...."
	g++-4.7 -std=c++11 -o professor_income project1_main.cpp
	chmod 740 professor_income
	@echo "Done! Type 'professor_income' and Enjoy the cookies."
